// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: config/keymap_config.yaml

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "driver/gpio.h"
#include "class/hid/hid.h"

typedef enum {
    MACRO_ACTION_NONE = 0,
    MACRO_ACTION_KEYBOARD,
    MACRO_ACTION_CONSUMER,
} macro_action_type_t;

typedef struct {
    gpio_num_t gpio;
    bool active_low;
    uint8_t led_index;
    macro_action_type_t type;
    uint16_t usage;
    const char *name;
} macro_action_config_t;

typedef struct {
    uint8_t r;
    uint8_t g;
    uint8_t b;
} macro_rgb_t;

typedef struct {
    uint16_t button_single_usage;
    uint16_t cw_usage;
    uint16_t ccw_usage;
} macro_encoder_layer_config_t;

typedef struct {
    uint16_t left_usage;
    uint16_t right_usage;
    bool left_hold_repeat;
    bool right_hold_repeat;
    uint16_t hold_start_ms;
    uint16_t hold_repeat_ms;
} macro_touch_layer_config_t;

#define MACRO_KEY_COUNT 12
#define MACRO_LAYER_COUNT 3

static const macro_action_config_t g_macro_keymap_layers[MACRO_LAYER_COUNT][MACRO_KEY_COUNT] = {
    // Layer 1 (default)
    {
        {GPIO_NUM_7, true, 3, MACRO_ACTION_KEYBOARD, HID_KEY_F13, "K1"},
        {GPIO_NUM_8, true, 4, MACRO_ACTION_KEYBOARD, HID_KEY_F14, "K2"},
        {GPIO_NUM_9, true, 5, MACRO_ACTION_KEYBOARD, HID_KEY_F15, "K3"},
        {GPIO_NUM_17, true, 6, MACRO_ACTION_KEYBOARD, HID_KEY_F16, "K4"},
        {GPIO_NUM_18, true, 10, MACRO_ACTION_KEYBOARD, HID_KEY_F17, "K5"},
        {GPIO_NUM_12, true, 9, MACRO_ACTION_KEYBOARD, HID_KEY_F18, "K6"},
        {GPIO_NUM_13, true, 8, MACRO_ACTION_KEYBOARD, HID_KEY_F19, "K7"},
        {GPIO_NUM_14, true, 7, MACRO_ACTION_KEYBOARD, HID_KEY_F20, "K8"},
        {GPIO_NUM_1, true, 11, MACRO_ACTION_KEYBOARD, HID_KEY_F21, "K9"},
        {GPIO_NUM_2, true, 12, MACRO_ACTION_KEYBOARD, HID_KEY_F22, "K10"},
        {GPIO_NUM_40, true, 13, MACRO_ACTION_KEYBOARD, HID_KEY_F23, "K11"},
        {GPIO_NUM_41, true, 14, MACRO_ACTION_KEYBOARD, HID_KEY_F24, "K12"},
    },
    // Layer 2
    {
        {GPIO_NUM_7, true, 3, MACRO_ACTION_KEYBOARD, HID_KEY_1, "K1"},
        {GPIO_NUM_8, true, 4, MACRO_ACTION_KEYBOARD, HID_KEY_2, "K2"},
        {GPIO_NUM_9, true, 5, MACRO_ACTION_KEYBOARD, HID_KEY_3, "K3"},
        {GPIO_NUM_17, true, 6, MACRO_ACTION_KEYBOARD, HID_KEY_4, "K4"},
        {GPIO_NUM_18, true, 10, MACRO_ACTION_KEYBOARD, HID_KEY_5, "K5"},
        {GPIO_NUM_12, true, 9, MACRO_ACTION_KEYBOARD, HID_KEY_6, "K6"},
        {GPIO_NUM_13, true, 8, MACRO_ACTION_KEYBOARD, HID_KEY_7, "K7"},
        {GPIO_NUM_14, true, 7, MACRO_ACTION_KEYBOARD, HID_KEY_8, "K8"},
        {GPIO_NUM_1, true, 11, MACRO_ACTION_KEYBOARD, HID_KEY_9, "K9"},
        {GPIO_NUM_2, true, 12, MACRO_ACTION_KEYBOARD, HID_KEY_0, "K10"},
        {GPIO_NUM_40, true, 13, MACRO_ACTION_KEYBOARD, HID_KEY_MINUS, "K11"},
        {GPIO_NUM_41, true, 14, MACRO_ACTION_KEYBOARD, HID_KEY_EQUAL, "K12"},
    },
    // Layer 3
    {
        {GPIO_NUM_7, true, 3, MACRO_ACTION_CONSUMER, HID_USAGE_CONSUMER_MUTE, "K1"},
        {GPIO_NUM_8, true, 4, MACRO_ACTION_CONSUMER, HID_USAGE_CONSUMER_VOLUME_DECREMENT, "K2"},
        {GPIO_NUM_9, true, 5, MACRO_ACTION_CONSUMER, HID_USAGE_CONSUMER_VOLUME_INCREMENT, "K3"},
        {GPIO_NUM_17, true, 6, MACRO_ACTION_CONSUMER, HID_USAGE_CONSUMER_PLAY_PAUSE, "K4"},
        {GPIO_NUM_18, true, 10, MACRO_ACTION_KEYBOARD, HID_KEY_F1, "K5"},
        {GPIO_NUM_12, true, 9, MACRO_ACTION_KEYBOARD, HID_KEY_F2, "K6"},
        {GPIO_NUM_13, true, 8, MACRO_ACTION_KEYBOARD, HID_KEY_F3, "K7"},
        {GPIO_NUM_14, true, 7, MACRO_ACTION_KEYBOARD, HID_KEY_F4, "K8"},
        {GPIO_NUM_1, true, 11, MACRO_ACTION_KEYBOARD, HID_KEY_F5, "K9"},
        {GPIO_NUM_2, true, 12, MACRO_ACTION_KEYBOARD, HID_KEY_F6, "K10"},
        {GPIO_NUM_40, true, 13, MACRO_ACTION_KEYBOARD, HID_KEY_F7, "K11"},
        {GPIO_NUM_41, true, 14, MACRO_ACTION_KEYBOARD, HID_KEY_F8, "K12"},
    },
};

static const macro_rgb_t g_layer_backlight_color[MACRO_LAYER_COUNT] = {
    {90, 90, 0},
    {0, 90, 0},
    {0, 0, 90},
};

#define MACRO_LED_INDICATOR_BRIGHTNESS 16
#define MACRO_LED_KEY_BRIGHTNESS 10
#define MACRO_LED_OFF_TIMEOUT_SEC 180
#define MACRO_LAYER_KEY_DIM_SCALE 45
#define MACRO_LAYER_KEY_ACTIVE_SCALE 140

static const macro_encoder_layer_config_t g_encoder_layer_config[MACRO_LAYER_COUNT] = {
    {HID_USAGE_CONSUMER_PLAY_PAUSE, HID_USAGE_CONSUMER_VOLUME_INCREMENT, HID_USAGE_CONSUMER_VOLUME_DECREMENT},
    {HID_USAGE_CONSUMER_SCAN_NEXT_TRACK, HID_USAGE_CONSUMER_VOLUME_INCREMENT, HID_USAGE_CONSUMER_VOLUME_DECREMENT},
    {HID_USAGE_CONSUMER_PLAY_PAUSE, HID_USAGE_CONSUMER_SCAN_NEXT_TRACK, HID_USAGE_CONSUMER_SCAN_PREVIOUS_TRACK},
};

static const macro_touch_layer_config_t g_touch_layer_config[MACRO_LAYER_COUNT] = {
    {HID_USAGE_CONSUMER_SCAN_PREVIOUS_TRACK, HID_USAGE_CONSUMER_SCAN_NEXT_TRACK, false, false, 0, 0},
    {HID_USAGE_CONSUMER_VOLUME_DECREMENT, HID_USAGE_CONSUMER_VOLUME_INCREMENT, true, true, 220, 110},
    {HID_USAGE_CONSUMER_BRIGHTNESS_DECREMENT, HID_USAGE_CONSUMER_BRIGHTNESS_INCREMENT, false, false, 0, 0},
};

#define MACRO_ENCODER_BUTTON_ACTIVE_LOW true
#define MACRO_ENCODER_TAP_WINDOW_MS 350
#define MACRO_ENCODER_SINGLE_TAP_DELAY_MS 120

#define MACRO_OLED_DEFAULT_BRIGHTNESS_PERCENT 70
#define MACRO_OLED_DIM_BRIGHTNESS_PERCENT 15
#define MACRO_OLED_DIM_TIMEOUT_SEC 45
#define MACRO_OLED_OFF_TIMEOUT_SEC 180
#define MACRO_OLED_SHIFT_RANGE_PX 2
#define MACRO_OLED_SHIFT_INTERVAL_SEC 60
#define MACRO_OLED_I2C_SCL_HZ 800000

#define MACRO_WIFI_PORTAL_ENABLED true
#define MACRO_WIFI_PORTAL_AP_SSID "MacroPad-Setup"
#define MACRO_WIFI_PORTAL_AP_PASSWORD "12345678"
#define MACRO_WIFI_PORTAL_AP_AUTH_MODE WIFI_AUTH_WPA3_ENTERPRISE
#define MACRO_WIFI_PORTAL_AP_CHANNEL 1
#define MACRO_WIFI_PORTAL_AP_MAX_CONNECTIONS 4
#define MACRO_WIFI_PORTAL_TIMEOUT_SEC 300
#define MACRO_WIFI_PORTAL_STA_CONNECT_TIMEOUT_MS 12000
#define MACRO_WIFI_PORTAL_STA_MAX_RETRY 3
#define MACRO_WIFI_PORTAL_SCAN_MAX_RESULTS 20
#define MACRO_WIFI_PORTAL_DNS_ENABLED true

#define MACRO_BUZZER_ENABLED true
#define MACRO_BUZZER_GPIO GPIO_NUM_21
#define MACRO_BUZZER_DUTY_PERCENT 28
#define MACRO_BUZZER_QUEUE_SIZE 16
#define MACRO_BUZZER_RTTTL_NOTE_GAP_MS 8

#define MACRO_BUZZER_STARTUP_ENABLED false
#define MACRO_BUZZER_RTTTL_STARTUP "mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p"

#define MACRO_BUZZER_KEYPRESS_ENABLED true
#define MACRO_BUZZER_RTTTL_KEYPRESS "key:d=32,o=6,b=180:c"

#define MACRO_BUZZER_LAYER_SWITCH_ENABLED true
#define MACRO_BUZZER_RTTTL_LAYER1 "l1:d=16,o=6,b=180:g"
#define MACRO_BUZZER_RTTTL_LAYER2 "l2:d=16,o=6,b=180:g,g"
#define MACRO_BUZZER_RTTTL_LAYER3 "l3:d=16,o=6,b=180:g,g,g"

#define MACRO_BUZZER_ENCODER_STEP_ENABLED true
#define MACRO_BUZZER_RTTTL_ENCODER_CW "cw:d=32,o=6,b=220:e"
#define MACRO_BUZZER_RTTTL_ENCODER_CCW "ccw:d=32,o=6,b=220:d"
#define MACRO_BUZZER_ENCODER_MIN_INTERVAL_MS 14
#define MACRO_BUZZER_ENCODER_TOGGLE_ENABLED false
#define MACRO_BUZZER_ENCODER_TOGGLE_TAP_COUNT 5
#define MACRO_BUZZER_RTTTL_TOGGLE_ON "bon:d=32,o=6,b=180:g"
#define MACRO_BUZZER_RTTTL_TOGGLE_OFF "boff:d=32,o=5,b=180:e"

#define MACRO_HA_ENABLED true
#define MACRO_HA_DEVICE_NAME "esp32-macropad"
#define MACRO_HA_EVENT_PREFIX "macropad"
#define MACRO_HA_REQUEST_TIMEOUT_MS 1800
#define MACRO_HA_QUEUE_SIZE 24
#define MACRO_HA_WORKER_INTERVAL_MS 30
#define MACRO_HA_MAX_RETRY 1
#define MACRO_HA_PUBLISH_LAYER_SWITCH true
#define MACRO_HA_PUBLISH_KEY_EVENT false
#define MACRO_HA_PUBLISH_ENCODER_STEP false
#define MACRO_HA_PUBLISH_TOUCH_SWIPE false
#define MACRO_HA_DISPLAY_ENABLED false
#define MACRO_HA_DISPLAY_ENTITY_ID "sensor.qmi_psv3_0a92_electric_power"
#define MACRO_HA_DISPLAY_LABEL "Power"
#define MACRO_HA_DISPLAY_POLL_INTERVAL_MS 3000
#define MACRO_HA_CONTROL_ENABLED false
#define MACRO_HA_CONTROL_TAP_COUNT 6
#define MACRO_HA_CONTROL_DOMAIN "switch"
#define MACRO_HA_CONTROL_SERVICE "switch_1"
#define MACRO_HA_CONTROL_ENTITY_ID "switch.zimi_zncz01_b58e_switch"

#define MACRO_WEB_SERVICE_ENABLED true
#define MACRO_WEB_SERVICE_PORT 8080
#define MACRO_WEB_SERVICE_MAX_URI_HANDLERS 16
#define MACRO_WEB_SERVICE_STACK_SIZE 6144
#define MACRO_WEB_SERVICE_RECV_TIMEOUT_SEC 5
#define MACRO_WEB_SERVICE_SEND_TIMEOUT_SEC 5
#define MACRO_WEB_SERVICE_CORS_ENABLED true
#define MACRO_WEB_SERVICE_CONTROL_ENABLED false

#define MACRO_OTA_ENABLED true
#define MACRO_OTA_CONFIRM_TAP_COUNT 3
#define MACRO_OTA_CONFIRM_TIMEOUT_SEC 120
#define MACRO_OTA_SELF_CHECK_DURATION_MS 2000
#define MACRO_OTA_SELF_CHECK_MIN_HEAP_BYTES 65536

#define MACRO_TOUCH_TRIGGER_PERCENT 85
#define MACRO_TOUCH_RELEASE_PERCENT 92
#define MACRO_TOUCH_TRIGGER_MIN_DELTA 3500
#define MACRO_TOUCH_RELEASE_MIN_DELTA 1800
#define MACRO_TOUCH_GESTURE_WINDOW_MS 650
#define MACRO_TOUCH_MIN_INTERVAL_MS 280
#define MACRO_TOUCH_BASELINE_FREEZE_TOTAL_DELTA 1200
#define MACRO_TOUCH_BASELINE_FREEZE_SIDE_DELTA 600
#define MACRO_TOUCH_CONTACT_MIN_TOTAL_DELTA 1500
#define MACRO_TOUCH_CONTACT_MIN_SIDE_DELTA 700
#define MACRO_TOUCH_START_SIDE_DELTA 250
#define MACRO_TOUCH_GESTURE_TRAVEL_DELTA 450
#define MACRO_TOUCH_SWIPE_SIDE_MIN_DELTA 1500
#define MACRO_TOUCH_SWIPE_SIDE_RELATIVE_PERCENT 20
#define MACRO_TOUCH_REQUIRE_BOTH_SIDES true
#define MACRO_TOUCH_BOTH_SIDES_HOLD_MS 50
#define MACRO_TOUCH_SIDE_SEQUENCE_MIN_MS 20
#define MACRO_TOUCH_START_DOMINANT_MIN_MS 30
#define MACRO_TOUCH_MIN_SWIPE_MS 100
#define MACRO_TOUCH_DIRECTION_DOMINANCE_DELTA 650
#define MACRO_TOUCH_SWAP_SIDES false
#define MACRO_TOUCH_DEBUG_LOG_ENABLE false
#define MACRO_TOUCH_DEBUG_LOG_INTERVAL_MS 80
#define MACRO_TOUCH_IDLE_NOISE_MARGIN 120
#define MACRO_TOUCH_IDLE_NOISE_MAX_DELTA 2400

